name: open_local_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
repository: 'github.com/WilliamKarolDiCioccio/open_local_ui'

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  unicons: ^2.1.1
  logger: ^2.2.0
  adaptive_theme: ^3.6.0
  url_launcher: ^6.2.6
  langchain: ^0.7.1
  langchain_ollama: ^0.2.1+1
  flutter_native_splash: ^2.4.0
  bitsdojo_window: ^0.1.6
  process_run: ^0.14.2
  http: ^1.2.1
  provider: ^6.1.2
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  conversion_units: ^0.1.8
  markdown: ^7.2.2
  system_theme: ^2.3.1
  flutter_highlight:
    path: ./packages/highlight.dart/flutter_highlight
  path_provider: ^2.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.0.1
  super_drag_and_drop: ^0.8.12
  flutter_markdown_selectionarea: ^0.6.17+1
  flutter_localizations:
    sdk: flutter
  intl: any
  file_picker: ^8.0.2
  flutter_image_converter: ^0.3.1
  image: ^4.1.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_animate: ^4.5.0
  supabase_flutter: ^2.5.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  envied: ^0.5.4+1
  feedback: ^3.1.0
  gap: ^3.0.1
  grpc: ^3.2.4
  protoc_plugin: ^21.1.2
  protobuf: ^3.1.0
  html: ^0.15.4
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1
  envied_generator: ^0.5.4+1

flutter:
  generate: true
  assets:
    - assets/prompts/default.txt
    - assets/prompts/title_generator.txt
  fonts:
    - family: ValeraRound
      fonts:
        - asset: assets/fonts/VarelaRound/VarelaRound-Regular.ttf
          style: normal
    - family: Neuton
      fonts:
        - asset: assets/fonts/Neuton/Neuton-Regular.ttf
          style: normal
        - asset: assets/fonts/Neuton/Neuton-Italic.ttf
          style: italic
        - asset: assets/fonts/Neuton/Neuton-Light.ttf
          weight: 300
        - asset: assets/fonts/Neuton/Neuton-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Neuton/Neuton-Bold.ttf
          weight: 700
        - asset: assets/fonts/Neuton/Neuton-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-VariableFont_wght.ttf
  uses-material-design: true
