name: Dart Format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1
            - name: Verify formatting
              run: dart format --outout=write --set-exit-if-changed .